### ISSUE TITLE
Compression Algorithm Error

### ISSUE THREAD

**Issue by ajschwieterman** [knowhowlab/keepass-maven-plugin#5]
I cannot load my KeePassXC file.  I get the following error below.  I can open the file with KeePassXC v2.5.3.  The file uses a master password to open it.

```
java.lang.IllegalArgumentException: Value 969983647 is not a valid CompressionAlgorithm
	at de.slackspace.openkeepass.domain.CompressionAlgorithm.parseValue(CompressionAlgorithm.java:14)
	at de.slackspace.openkeepass.domain.KeePassHeader.setCompressionFlag(KeePassHeader.java:271)
	at de.slackspace.openkeepass.domain.KeePassHeader.setValue(KeePassHeader.java:65)
	at de.slackspace.openkeepass.domain.KeePassHeader.read(KeePassHeader.java:144)
	at de.slackspace.openkeepass.KeePassDatabase.<init>(KeePassDatabase.java:104)
	at de.slackspace.openkeepass.KeePassDatabase.getInstance(KeePassDatabase.java:165)
	at de.slackspace.openkeepass.KeePassDatabase.getInstance(KeePassDatabase.java:138)
	at org.knowhowlab.maven.plugins.keepass.dao.KeePassDAO.<init>(KeePassDAO.java:38)
```

**Comment by dpishchukhin** [comment]
@ajschwieterman, thank you for feedback.

can you provide any steps to reproduce?

**Comment by ajschwieterman** [comment]
I figured out the problem!  I switched the database format from KDBX 4.0 to KDBX 3.1, and that worked.
